import os
import os.path as path
from shutil import rmtree


def generate_mock_folder():
	if path.exists(path.join(path.dirname(__file__), "mock")):
		rmtree("mock")
	os.mkdir("mock")
	with open("mock/a.txt", "w") as a:
		a.write("""The Hundred Years' War was a series of conflicts waged from 1337 to 1453 by the House of Plantagenet, rulers of the Kingdom of England, against the French House of Valois, over the right to rule the Kingdom of France. Each side drew many allies into the war. It was one of the most notable conflicts of the Middle Ages, in which five generations of kings from two rival dynasties fought for the throne of the largest kingdom in Western Europe. The war marked both the height of chivalry and its subsequent decline, and the development of strong national identities in both countries.
		Tensions between the crowns of France and England can be traced back to the origins of the English royal family itself, which was French (Norman, and later, Angevin) in origin. For this reason, English monarchs had historically held not only the English crown, but also titles and lands within France, the possession of which made them vassals to the kings of France. The status of the English king's French fiefs was a major source of conflict between the two monarchies throughout the Middle Ages. French monarchs systematically sought to check the growth of English power, stripping away lands as the opportunity arose, particularly whenever England was at war with Scotland, an ally of France. Over the centuries, English holdings in France had varied in size, at some points dwarfing even the French royal domain; by 1337, however, only Gascony was left to the English.
		In 1316, a principle was established denying women succession to the French throne (later retroactively attributed to the ancient Salic law). In 1328, Charles IV of France died without sons or brothers. His closest male relative was his nephew Edward III of England, whose mother, Isabella of France, was sister of the deceased king. Isabella claimed the throne of France for her son, but the French rejected it, maintaining that Isabella could not transmit a right she did not possess. Furthermore, political sentiment favoured a Frenchman for the crown rather than a foreign prince. The throne passed instead to Philip, Count of Valois, a patrilineal cousin of Charles IV, who would become Philip VI of France, the first king of the House of Valois. The English had not expected their claim to meet with success, and did not press the matter when it was denied. However, disagreements between Philip and Edward induced the former to confiscate the latter's lands in France, and in turn prompted Edward III to reassert his claim to the French throne.
		Several overwhelming English victories in the war—especially at Crécy, Poitiers, Agincourt and Verneuil—raised the prospects of an ultimate English triumph, and persuaded the English to continue pouring money and manpower into the war over many decades. However, the death of Henry V and succession of his infant son, with the dysfunctional government that ruled and the loss of Burgundy as an ally, prevented the English kings from ever completing the conquest of France. Starting in 1429, decisive French victories at Orléans, Patay, Formigny, and later Castillon concluded the war in favour of the House of Valois, with England permanently losing most of its possessions on the continent.""")
	with open("mock/b.txt", "w") as b:
		b.write("""The Eighty Years' War (Dutch: Tachtigjarige Oorlog; Spanish: Guerra de los Ochenta Años) or Dutch War of Independence (1568–1648)[2] was a revolt of the Seventeen Provinces of what are today the Netherlands, Belgium, and Luxembourg against Philip II of Spain, the sovereign of the Habsburg Netherlands. After the initial stages, Philip II deployed his armies and regained control over most of the rebelling provinces. Under the leadership of the exiled William the Silent, the northern provinces continued their resistance. They eventually were able to oust the Habsburg armies, and in 1581 they established the Republic of the Seven United Netherlands. The war continued in other areas, although the heartland of the republic was no longer threatened. This included the origins of the Dutch colonial empire, which began with Dutch attacks on Portugal's overseas territories, which at the time was conceived as carrying overseas the war with Spain due to Portugal being in a dynastic union with Spain. The Dutch Republic was recognized by Spain and the major European powers in 1609 at the start of the Twelve Years' Truce. Hostilities broke out again around 1619, as part of the broader Thirty Years' War. An end was reached in 1648 with the Peace of Münster (a treaty part of the Peace of Westphalia), when the Dutch Republic was definitively recognised as an independent country no longer part of the Holy Roman Empire. The Peace of Münster is sometimes considered the beginning of the Dutch Golden Age.""")
	with open("mock/c.ab.txt", "w") as b:
		b.write("Hello Land this is a test thing #3.\nIt's a pretty quality test thing.")
