#!/usr/bin/env python
from os import path
from src.DocumentOrganizer import DocumentOrganizer
import spacy
import click
from click import echo


@click.command()
@click.argument("directory")
def run(directory):
	nlp = spacy.load("en_core_web_lg")
	organizer = DocumentOrganizer(path.abspath(directory), nlp)
	print(organizer.base_dir)
	for file in organizer.document_loader.files:
		organizer.sort_file(file)
	organizer.move_files()
	echo("Done")


if __name__ == "__main__":
	run()
